# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  environment: dev
  appname: api
  warname: default
jobs:
  
  test: 
   runs-on: ubuntu-latest
   steps: 
    - name: Preparation env 
      run: |
        echo "environment=dev" >> $GITHUB_OUTPUT
        echo "warname=penup-234234.war" >> $GITHUB_OUTPUT 
          echo "appname=open" >> $GITHUB_OUTPUT 
      id: extract
  
    - name: Verification 
      run: |
        echo ${{ steps.extract.outputs.environment }}
        echo ${{ steps.extract.outputs.warname }}
        echo "warname=${{ steps.extract.outputs.warname }}" >> "$GITHUB_ENV"
        echo "environment=${{ steps.extract.outputs.environment }}" >> "$GITHUB_ENV"
        echo "appname=${{ steps.extract.outputs.appname }}" >> "$GITHUB_ENV"
 
  call-workflow:
    needs: 
      test
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/build.yml
    with:
          # with 키워드로 넘겨받은 env, region 값으로 판단하여 그에 맞는 빌드를 하겠죠?
          environment: ${{env.environment}} 
          appname: ${{env.appname }}
          warname: ${{env.warname }}
    secrets:
      envPAT: ${{ secrets.envPAT }}

      
