# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  environment: dev
  appname: api
  warname: default
jobs:
  
  test: 
   runs-on: ubuntu-latest
   steps: 
    - name: Preparation env 
      run: |
        echo "::set-output name=environment::dev"
        echo "::set-ouput name=warname::penup-234234.war"
      id: extract
  
    - name: Verification 
      run: |
        echo ${{ steps.extract.outputs.environment }}
        echo ${{ steps.extract.outputs.warname }}
        echo "warname=${{ steps.extract.outputs.warname }}" >> "$GITHUB_ENV"
        echo "environment=${{ steps.extract.outputs.environment }}" >> "$GITHUB_ENV"
        
      env:
          warname: ${{ steps.extract.outputs.warname }}
  call-workflow:
    needs: 
      test
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/build.yml
    with:
          # with 키워드로 넘겨받은 env, region 값으로 판단하여 그에 맞는 빌드를 하겠죠?
          environment: $environment 
          appname: ${{vars.appname }}
          warname: $warname 
    secrets:
      envPAT: ${{ secrets.envPAT }}

      
